//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP_LEGASPI_CPE201.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OOP_LEGASPI_CPE201.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ALL_MEAT_WHOLE_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("ALL MEAT WHOLE PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ALL_MEAT_WHOLE_PIZZA_18inches1 {
            get {
                object obj = ResourceManager.GetObject("ALL MEAT WHOLE PIZZA 18inches1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CHEESE_WHOLE_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("CHEESE WHOLE PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CHEESY_BURGER_DELUXE_PIZZA_WHOLE_18inches {
            get {
                object obj = ResourceManager.GetObject("CHEESY BURGER DELUXE PIZZA WHOLE 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMBO_AND_CHEESE_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("COMBO AND CHEESE PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMBO_AND_GARLIC_SHRIMP_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("COMBO AND GARLIC SHRIMP PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMBO_AND_PEPPERONI_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("COMBO AND PEPPERONI PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMBO_WHOLE_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("COMBO WHOLE PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CREAM_CHEESE_PEPPERONI_WHOLE_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("CREAM-CHEESE PEPPERONI WHOLE PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GARLIC_AND_SHRIMP_WHOLE_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("GARLIC AND SHRIMP WHOLE PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GARLIC_SHRIMP_AND_CHEESE_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("GARLIC SHRIMP AND CHEESE PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GARLIC_SHRIMP_AND_PEPPERONI_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("GARLIC SHRIMP AND PEPPERONI PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HOLIDAY_PIZZA {
            get {
                object obj = ResourceManager.GetObject("HOLIDAY PIZZA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PEPPERONI_AND_CHEESE_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("PEPPERONI AND CHEESE PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PEPPERONI_WHOLE_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("PEPPERONI WHOLE PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TROPICAL_HAWAIIAN_WHOLE_PIZZA_18inches {
            get {
                object obj = ResourceManager.GetObject("TROPICAL HAWAIIAN WHOLE PIZZA 18inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
